### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by applehat** [thebookins/xdrip-js#3]
Hey man,

I was planning to start implementing some xDripG5 on OpenAPS rigs stuff... but I see you've already started.

Whats the current status of this code?

I'd love to help!

**Comment by thebookins** [comment]
Hey,
I'd love some help with this!!

So where I'm up to: I could get the code working on Mac OS, and reading successfully from the G5. I can calibrate and start and stop sensor, and working towards a simple web app to act as the local user interface. I've also found out how to read backfill messages.

Where I'm stuck: As far as I can determine, the G5 requires LE Secure Connections (i.e. it shares a IRK with the host as part of the pairing process). The Intel Edison doesn't support this type of pairing, because the kernel on the Edison is very old. I don't know how practical it is to upgrade the kernel, but there are some instructions for doing this. @PieterGit knows about it.

What next: I'm thinking of parking the Edison work for a bit, and just trying to get everything to work on a laptop running the latest Ubuntu or something. Once that's all good, tackle the kernel on the Edison. However, with the discontinuation of the Edison, it might be more productive to move to the Pi zero. Not sure about support for LE Secure Connections on the Pi Zero.

What do you think?

**Comment by applehat** [comment]
If you have some docs on how to get me up and running (command line commands or whatever) I can test on a Pi 3 - same Bluetooth stack as the Zero.

I agree on moving forward with it on a newer kernel. There's no reason a new Jubilinux couldn't be built - or with the Edison death the Pi Zero rig (that I'm assuming will probably become standard) already (most likely) has a new enough kernel.

I also have some cool ideas about calibration and such.

Want to start a gitter channel, or find me on Facebook, and we can chat more?

**Comment by thebookins** [comment]
Hi Cameron, let's chat on https://gitter.im/thebookins/xdrip-js.

If you have a look at [the wiki](https://github.com/thebookins/xdrip-js/wiki) there are some installation details. Basically, you need a recent version of nodejs and any dependencies for noble. Then after cloning this repo call `npm install`. To run: `node example <######>` where <######> is the transmitter ID.

The documentation is a bit sketchy - hit me up on Gitter if you run into trouble.

**Comment by PieterGit** [comment]
Recent kernels for Pi zero will probably support LE Secure Connections. I still plan to work on a Debian 9.0 and Kernel 4.12 image for Edison, but other things are first on my list. Links if anybody is interested:
- https://communities.intel.com/thread/75472?start=105&tstart=0 (EDS-branch is available on 4.12 now)
- https://edison.internet-share.com/wiki/Using_a_vanilla_Linux_kernel_with_Intel_Edison (invalid certifcate)

**Comment by thebookins** [comment]
Closing - see https://gitter.im/thebookins/xdrip-js for project status.
